### ISSUE TITLE
REPL: v.0.2.0

### ISSUE THREAD

**Issue by azinit** [feature-sliced/repl#4]
## Steps

- [ ] REPL: Convertation to MD snippet
- [ ] REPL: Diff of two structures
- [ ] REPL: Definition of Public API of modules
- [ ] REPL: Definition of modules relations
- [ ] REPL: Convertation to project template
- [ ] REPL: Definition of lint-boundaries
